### ISSUE TITLE
Minor edit with only one public version breaks translation status

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#1464]
### Describe the Bug

When I publish a translation (from draft to published) with the tick set at small edit, the status is not updated
### Steps to Reproduce

1. Go to a page with translation (in draft status)
2. Click on any translation 
3. Change something
4. Put the tick at small edit
5. Press update/publish

### Expected Behavior

The current version, as indicated in the timeline, should be the one which is published. If the status was draft, the status should change to published after clicking publish. 

### Actual Behavior

In the case of a draft page, the status is not changed.

**Comment by osmers** [comment]
I can try and make a video to show the behaviour
Possible solution in the case of updating a draft page - automatically disable/ignore the small edit check box once published is pressed as generally the intention upon pressing publish should be that the page is published.
In the case of an already published page, the check box should not affect the delivered version.

**Comment by MizukiTemma** [comment]
I have tried to reproduce the bug in the following steps:
1. create a new page and publish it (one public version, version 1).
2. make some changes and save it as draft (translation in draft status, version2).
3. make some changes and publish it as minor edit (version3).

All those are done in the german version.

The translation version3 is marked as published and also as the version shown in the app.
Though "translation missing" is shown.

Is this "translation missing" the problem?

The status change between draft and published seems to be working.

**Comment by timoludwig** [comment]
> The translation version3 is marked as published and also as the version shown in the app. Though "translation missing" is shown.
> 
> Is this "translation missing" the problem?

Yes, I think this is essentially the same problem as in the initial issue description.
Another way to reproduce the bug is to create a page as public, then without making changes click on "minor edit" and "update" - then, it's still only one version, which is both public and minor, which seems to break the status.

**Comment by MizukiTemma** [comment]
Ah, ok. Thank you. Now I got it :)

**Comment by svenseeberg** [comment]
@osmers we need to revisit this. Initially you stated:

> When I publish a translation (from draft to published) with the tick set at small edit, the status is not updated

However, this is exactly what the "minor edit" function is about. If you want to update the translation status, the "minor edit" should not be checked.

Maybe we need to rename "minor edit" to "ignore in translation status" ?

**Comment by timoludwig** [comment]
> Whether a page is a draft or published should have no influence on the state of a translation.

That's not entirely correct, since we defined draft versions as "missing" translation because they are not shown in the apps.
So when there are only draft versions, and then a minor change is made (e.g. changing a typo in the German text) and directly published, the translation state should change from "missing" to "up to date", even if the latest version is only minor. This is essentially what this ticket is for.

My suggestion in this case was to publish all past versions as well, but only if the publish button is clicked...

**Comment by timoludwig** [comment]
> Alright, then I would reason that we should get rid of this agreement. This behavior is not directly derivable from the functionality and needs additional knowledge.

Ok, debatable. On the other hand, it prevents simple misunderstandings like "I see a green check mark, so why is the page not shown in language xy?"... When implementing this feature, the service team already put quite some thought in the existing conventions (which does not make them unchangeable for all eternity, but we should at least consider the original arguments).

> Why not simply NOT check the minor edit checkbox? I think we're complicating the usage of this functionality by introducing conventions. And maybe that is a good example why we should rename the checkbox to something that actually explains what it is supposed to do?

Well, let's consider the following scenario: German and English are up to date, but in draft state. Then, they notice a typo in the German text, fix it and decide it's now time to publish the page. If they don't mark it as minor edit, the English translation will be marked as outdated as soon as it's published, even if it isn't, because the typo change does not require a change of the translation.

I'm open for renaming the checkbox, but I don't think it solves our problem (and I think the existing help text explains what's happening pretty well)...

**Comment by svenseeberg** [comment]
> Well, let's consider the following scenario: German and English are up to date, but in draft state. Then, they notice a typo in the German text, fix it and decide it's now time to publish the page. If they don't mark it as minor edit, the English translation will be marked as outdated as soon as it's published, even if it isn't, because the typo change does not require a change of the translation.

Well, if you forget to set the checkbox then there is not much that can be done, right? Then you need to hit the Save button for the translation as well without the minor edit button. That should fix it, doesn't it?

**Comment by timoludwig** [comment]
> Well, if you forget to set the checkbox then there is not much that can be done, right?

I didn't mean that one might forget to click the checkbox, but wanted to argue that your suggestion "_why not simply NOT check the minor edit checkbox?_" wouldn't make sense here :sweat_smile: 

> Then you need to hit the Save button for the translation as well without the minor edit button. That should fix it, doesn't it?

Yes, this is a workaround, but when there are 20 translations, this becomes a very tedious task. I would much rather prefer that the status is set correctly in the first place.


But this topic is kind of crazy, I'm not sure I completely understand it :see_no_evil:

**Comment by svenseeberg** [comment]
> But this topic is kind of crazy, I'm not sure I completely understand it see_no_evil

I sadly feel the same. I cannot wrap my head around all possible scenarios. That's why I created this list in https://github.com/digitalfabrik/integreat-cms/issues/1622#issuecomment-1204932908

**Comment by svenseeberg** [comment]
> Yes, this is a workaround, but when there are 20 translations, this becomes a very tedious task. I would much rather prefer that the status is set correctly in the first place.

For such a use case we could introduce a bulk action for marking multiple translations as up to date?

**Comment by osmers** [comment]
I am sorry I'm late to the conversation - it seems like you already fixed it? Or found a solution? I just tried again and the issue persists (probably bcs the release where this is fixed isn't through yet?). 
I'm not sure how relevant this issue is since I don't think we had this problem with a Kommune yet...I think it is just the definitions of translation status that we have and what Kommunen would understand are different. 
Published vs. draft to them IS NOT a translation status to them
up to date vs outdated IS a translation status
So marking the check box I would pressume that clicking publish should still publish the German page (even if there are no other translations yet) - but it does not do that. 
And yes, you are right @svenseeberg - they can just uncheck the box, but if their understanding is different, then that might not happen.

Also, if I try and publish a page while having the check box active the blue button does change from publish to update even though the status in the language tabs is shown as missing (however, the status label reads published)

![image](https://user-images.githubusercontent.com/64901227/183236027-6103bbe5-1b57-4706-9095-da30b1475492.png)
![image](https://user-images.githubusercontent.com/64901227/183236044-f984a571-b088-4f6d-8cb3-3166e9720097.png)

There is something else that I noticed - but I will leave it be for now, bcs this is already complicated enough and the new issue is probably something that will never come up.
